"""
Milestone 4 unit tests:
  - Spectral derivative matches the analytic derivative for a known field.
  - The Orszag 2/3 dealias mask removes aliased modes generated by a
    quadratic product (demonstrating the mechanism the RHS pipeline relies on).
  - The advection term (v.grad)v matches its analytic value for a simple
    shear-free sinusoidal flow.
  - The Lorentz force J x B matches its analytic value for the
    A = (0,0,sin x) test field used in Milestone 2.
  - R_A (Hall-MHD induction RHS) satisfies the Coulomb gauge: k.R_A_hat = 0.
  - R_v (incompressible NS forcing) satisfies div(v)-consistency: k.R_v_hat = 0.

Run with: pytest tests/test_milestone4.py
"""
import os
import sys

import numpy as np
import pytest

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'python')))
import hopfnet.hopfnet_cpp as eng
from hopfnet import rhs

N = 8
L = 2 * np.pi


def random_complex_field(rng, shape):
    return rng.standard_normal(shape) + 1j * rng.standard_normal(shape)


def random_vector_hat(grid, fft, rng):
    """A random, Coulomb-projected (divergence-free) complex vector field."""
    Nzh = grid.Nz_half
    f = tuple(random_complex_field(rng, (N, N, Nzh)) for _ in range(3))
    return eng.project_field(grid, *f)


def test_spectral_derivative_matches_analytic():
    grid = eng.SpectralGrid(N, L)
    fft = eng.FFT3D(N)

    x = np.arange(N) * (L / N)
    X, _, _ = np.meshgrid(x, x, x, indexing='ij')

    field = np.cos(X)
    field_hat = fft.forward(field)

    deriv_hat = rhs.spectral_derivative(grid, field_hat, axis=0)
    deriv_real = fft.inverse(deriv_hat)

    np.testing.assert_allclose(deriv_real, -np.sin(X), atol=1e-12)


def test_dealias_removes_aliased_mode():
    fft = eng.FFT3D(N)
    grid = eng.SpectralGrid(N, L)

    x = np.arange(N) * (L / N)
    X, _, _ = np.meshgrid(x, x, x, indexing='ij')

    # cos(3x)*cos(2x) = 0.5*[cos(5x) + cos(x)]. On an N=8 grid, mode 5
    # aliases to mode 5-8=-3 (index N-3=5), which lies OUTSIDE the
    # 2/3 cutoff (=2) and must be removed by the dealias mask.
    f = np.cos(3 * X)
    g = np.cos(2 * X)
    product = f * g

    product_hat = fft.forward(product)
    aliased_index = N - 3  # corresponds to integer wavenumber n=-3

    # Without dealiasing, the aliased mode is populated.
    assert np.abs(product_hat[aliased_index, 0, 0]) > 1e-6

    # After applying the dealias mask, it must be exactly zero.
    masked_hat = rhs.apply_dealias(grid, (product_hat,))[0]
    assert masked_hat[aliased_index, 0, 0] == 0.0

    # The surviving mode (n=+1, from cos(x)) must be untouched.
    assert masked_hat[1, 0, 0] == product_hat[1, 0, 0]


def test_advection_matches_analytic():
    # v = (sin(x), 0, 0)  =>  (v.grad)v = (vx * d(vx)/dx, 0, 0)
    #                                   = sin(x)cos(x) = 0.5*sin(2x)
    grid = eng.SpectralGrid(N, L)
    fft = eng.FFT3D(N)

    x = np.arange(N) * (L / N)
    X, _, _ = np.meshgrid(x, x, x, indexing='ij')

    vx = np.sin(X)
    vy = np.zeros((N, N, N))
    vz = np.zeros((N, N, N))
    v_hat = rhs.to_hat(fft, (vx, vy, vz))

    adv_hat = rhs.compute_advection(grid, fft, v_hat)
    adv_real = rhs.to_real(fft, adv_hat)

    np.testing.assert_allclose(adv_real[0], 0.5 * np.sin(2 * X), atol=1e-12)
    np.testing.assert_allclose(adv_real[1], np.zeros((N, N, N)), atol=1e-12)
    np.testing.assert_allclose(adv_real[2], np.zeros((N, N, N)), atol=1e-12)


def test_lorentz_force_matches_analytic():
    # A = (0,0,sin x)  =>  B = (0,-cos x,0)  =>  J = curl(B) = (0,0,sin x)
    # J x B = (-Jz*By, 0, 0) = (sin(x)*cos(x), 0, 0) = (0.5*sin(2x), 0, 0)
    grid = eng.SpectralGrid(N, L)
    fft = eng.FFT3D(N)

    x = np.arange(N) * (L / N)
    X, _, _ = np.meshgrid(x, x, x, indexing='ij')

    Ax = np.zeros((N, N, N))
    Ay = np.zeros((N, N, N))
    Az = np.sin(X)
    A_hat = rhs.to_hat(fft, (Ax, Ay, Az))
    A_hat = eng.project_field(grid, *A_hat)

    B_hat, J_hat = rhs.compute_B_and_J(grid, A_hat)
    B_real = rhs.to_real(fft, B_hat)
    J_real = rhs.to_real(fft, J_hat)

    JxB = rhs.cross_real(J_real, B_real)

    np.testing.assert_allclose(JxB[0], 0.5 * np.sin(2 * X), atol=1e-12)
    np.testing.assert_allclose(JxB[1], np.zeros((N, N, N)), atol=1e-12)
    np.testing.assert_allclose(JxB[2], np.zeros((N, N, N)), atol=1e-12)


def test_R_A_satisfies_coulomb_gauge():
    grid = eng.SpectralGrid(N, L)
    fft = eng.FFT3D(N)
    rng = np.random.default_rng(7)

    A_hat = random_vector_hat(grid, fft, rng)
    v_hat = random_vector_hat(grid, fft, rng)
    B_hat, J_hat = rhs.compute_B_and_J(grid, A_hat)

    R_hat = rhs.compute_R_A(grid, fft, v_hat, B_hat, J_hat, eta=0.01, d_i=0.1)

    KX, KY, KZ = rhs._k_arrays(grid)
    k_dot_R = KX * R_hat[0] + KY * R_hat[1] + KZ * R_hat[2]

    k2 = grid.k2()
    nonzero = k2 > 1e-14
    assert np.allclose(k_dot_R[nonzero], 0.0, atol=1e-10)


def test_R_v_satisfies_divergence_free_projection():
    grid = eng.SpectralGrid(N, L)
    fft = eng.FFT3D(N)
    rng = np.random.default_rng(11)

    v_hat = random_vector_hat(grid, fft, rng)
    A_hat = random_vector_hat(grid, fft, rng)
    B_hat, J_hat = rhs.compute_B_and_J(grid, A_hat)

    R_hat = rhs.compute_R_v(grid, fft, v_hat, B_hat, J_hat)

    KX, KY, KZ = rhs._k_arrays(grid)
    k_dot_R = KX * R_hat[0] + KY * R_hat[1] + KZ * R_hat[2]

    k2 = grid.k2()
    nonzero = k2 > 1e-14
    assert np.allclose(k_dot_R[nonzero], 0.0, atol=1e-10)


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
